project:
  type: website
  output-dir: docs

website:
  title: "temp_web"
  favicon: favicon.png
  navbar:
    logo: favicon.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: funfacts.qmd
        text: Fun Facts
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



